### ISSUE TITLE
GitKraken Swag

### ISSUE THREAD

**Issue by aytekk** [swapagarwal/swag-for-dev#198]
- [ + ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?
A. : GitKraken

Q. Where have you seen the announcement (URL)?
A. : https://www.gitkraken.com/invite/xhHK72Lk

Q. What kind of swag (clothing, stickers, ...)?
A. : Nintendo switch

Q. Have you received swag from this?
A. : No

Q. How long did it take?
A. : N/A

Q. Does it ship worldwide?
A. : Yes

--> If you're student, FREE pro account ! (Join github student pack and be pro)

**Comment by GuyKh** [comment]
Note that this link is referral.
Not sure this group's policy about that.

**Comment by aytekk** [comment]
When you refer someone to GitKraken and they click your custom link to create a free account, you are both entered to win a Nintendo Switch.

Otherwise, you can't.

**Comment by swapagarwal** [comment]
Thanks for bringing this up!
So we considered adding events / hacks / challenges. The reason for not including them was they are mostly competitive, whereas the current items on devSwag are more of an individual thing. If you do something, you get what was promised (no external factors involved).

---- On Wed, 05 Dec 2018 13:02:14 +0530 notifications@github.com wrote ----

Note that this link is referral.
Not sure this group's policy about that.

**Comment by swapagarwal** [comment]
I'm not in favor of featuring it. What do you guys think? @aslafy-z @vikaspotluri123

**Comment by arshadkazmi42** [comment]
> The reason for not including them was they are mostly competitive, whereas the current items on devSwag are more of an individual thing.

I am also not in favour of this. As I use this site only for the freebies, which I will get for sure, for doing something.
For competitive swags or lucky draws there are many other sites available. Let's keep devswag.io as it is.

**Comment by vikaspotluri123** [comment]
I agree. 

For now:

- Referral links are acceptable (because that's kind of the point of them), but if we start getting low-quality submissions just for the referral, we can always re-evaluate these guidelines.

- Submissions which have very low participation:"winner" ratio will be rejected (hacktoberfest can technically be considered a competition because there's a limited number of t-shirts, but the ratio of partipication:recepients is high!)

I'm going to close this for now, but we can definitely continue the discussion here or in gitter
