### ISSUE TITLE
Does devSwag need a new logo?

### ISSUE THREAD

**Issue by ardaald** [swapagarwal/swag-for-dev#200]
- [x] I've checked that this isn't a duplicate issue.

I'm a design student, and i would like to contribute to the visual design and the logo of this project along with other the members of the community who are interested.

**Comment by SemperDisco** [comment]
I think a logo would be sweet! I would like to be part of the process and offer feedback when you have some designs.

**Comment by ardaald** [comment]
![devswag-01](https://user-images.githubusercontent.com/44159669/49520362-69039400-f8a3-11e8-9c9b-01a23d29e4d5.png)

**Comment by vikaspotluri123** [comment]
Hey @ardaald do you want to create a PR to integrate it into the site?

@swapagarwal do you have any issues with the logo?

**Comment by swapagarwal** [comment]
Current:
![](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/155/smiling-face-with-sunglasses_1f60e.png)
Proposed:
![](https://user-images.githubusercontent.com/44159669/49520362-69039400-f8a3-11e8-9c9b-01a23d29e4d5.png)

Maybe increase the smile a little bit to increase the swag level (see current).
@plibither8 can provide more feedback here.

**Comment by aslafy-z** [comment]
As it's a pretty simple logo, would be great to have a vectorised version of it, a SVG version.
Do someone known something about creating those?

**Comment by ardaald** [comment]
Hey @aslafy-z @vikaspotluri123 @swapagarwal   here is the SVG version with a bigger smile! https://drive.google.com/open?id=1lTtb36JiVELPAwiMpXIVe0vCPI3rJfmk

**Comment by aslafy-z** [comment]
I think you should remove the text from the image so we can integrate it better where we want.

**Comment by SemperDisco** [comment]
@ardaald Thank you! It looks better now.

**Comment by SemperDisco** [comment]
@ardaald @vikaspotluri123 @swapagarwal If you guys approve the logo, can I add it to the website?

**Comment by ardaald** [comment]
Here is the logo without the text,  in any case the font was Rockwell! https://drive.google.com/open?id=1mFxiac_nIFHUG2HdarRDhx2MniSV9ERB

**Comment by vikaspotluri123** [comment]
@SemperDisco only of @ardaald doesn't want to 😉

**Comment by aslafy-z** [comment]
You can reduce the SVG size by using this website: https://jakearchibald.github.io/svgomg/

**Comment by agarwalml** [comment]
Hey! I really appreciate the work on the site and fell upon this thread.I created some renditions for the logo. Would appreciate some feedback.
P.S. I've uploaded a PNG of the logos, but I have SVGs ready.
![devswag_concepts](https://user-images.githubusercontent.com/42957482/49663319-41aff100-fa74-11e8-8cbc-43d7a9fd38b2.png)

**Comment by vikaspotluri123** [comment]
Just putting this out there, if we get a new logo, we should probably have a new icon too! There's no mutual exclusion here 😊

**Comment by plibither8** [comment]
Hey Vikas, how are we differentiating _logo_ and _icon_ here?

**Comment by vikaspotluri123** [comment]
icon = square, logo = rectangular

So wherever we need something square, we use the icon, and everywhere else we use the logo!

**Comment by agarwalml** [comment]
I agree. A logo needs to be responsive. The minimal ID can serve as a simple icon as well imo. Nothing too fancy

**Comment by SemperDisco** [comment]
@agarwalml I like the first one, it is pretty clean. 

Maybe we can also make an option which combines the logo from @ardaald with one of @agarwalml logos. 

Is it possible to host some sort of poll to vote on which logo to use?

**Comment by agarwalml** [comment]
@SemperDisco though it sounds like a good idea, don't you think by combining both logos & having 2 sticker based logos next to each other would over-do the design?

**Comment by SemperDisco** [comment]
@agarwalml Maybe you are right. I'm no designer I was just throwing ideas out there.

@plibither8 We can use https://app.gh-polls.com/

**Comment by plibither8** [comment]
Sure, that seems like a possible way to do it. Go ahead and create it :smile:

**Comment by agarwalml** [comment]
Since no one commented, here you go: 

[![](https://api.gh-polls.com/poll/01CY98B1NFH40PAZV6RJ470PKC/%40arbaald%20sticker%20emoji)](https://api.gh-polls.com/poll/01CY98B1NFH40PAZV6RJ470PKC/%40arbaald%20sticker%20emoji/vote)
[![](https://api.gh-polls.com/poll/01CY98B1NFH40PAZV6RJ470PKC/%40agarwalml%20logo%20sticker%201)](https://api.gh-polls.com/poll/01CY98B1NFH40PAZV6RJ470PKC/%40agarwalml%20logo%20sticker%201/vote)
[![](https://api.gh-polls.com/poll/01CY98B1NFH40PAZV6RJ470PKC/%40agarwalml%20filled%20logo%20sticker)](https://api.gh-polls.com/poll/01CY98B1NFH40PAZV6RJ470PKC/%40agarwalml%20filled%20logo%20sticker/vote)
[![](https://api.gh-polls.com/poll/01CY98B1NFH40PAZV6RJ470PKC/%40agarwalml%20logo%20ID)](https://api.gh-polls.com/poll/01CY98B1NFH40PAZV6RJ470PKC/%40agarwalml%20logo%20ID/vote)
[![](https://api.gh-polls.com/poll/01CY98B1NFH40PAZV6RJ470PKC/%40agarwalml%20logo%20ID%20w%2F%20strap)](https://api.gh-polls.com/poll/01CY98B1NFH40PAZV6RJ470PKC/%40agarwalml%20logo%20ID%20w%2F%20strap/vote)
[![](https://api.gh-polls.com/poll/01CY98B1NFH40PAZV6RJ470PKC/%40agarwalmlml%20logo%20sticker%202)](https://api.gh-polls.com/poll/01CY98B1NFH40PAZV6RJ470PKC/%40agarwalmlml%20logo%20sticker%202/vote)

P.S. This may be flawed as it's not restricted to one person one vote. So let's have it on an Honor basis. My logos are ordered as in the pic above (top to bottom)

**Comment by plibither8** [comment]
Pinging @swapagarwal

**Comment by SemperDisco** [comment]
@agarwalml Your entry named logo sticker 1 is probably the winner, I don't think the poll will change drastically from this point. Could you make a (fav)icon of the logo?

**Comment by SemperDisco** [comment]
@agarwalml Could you also add the svg?

**Comment by agarwalml** [comment]
Sharing the ID card logo as a favicon
https://drive.google.com/file/d/1J3Y3RP2oznG9TwSsECHwbI9J6fqzsyEp/view?usp=sharing

**Comment by SemperDisco** [comment]
Yes, that is okay. Thank you for providing the assets.

**Comment by swapagarwal** [comment]
Awesome! Let's get this integrated.

**Comment by SemperDisco** [comment]
@swapagarwal I'm working on it! ;)

**Comment by agarwalml** [comment]
Guys, any updates?

**Comment by aslafy-z** [comment]
It's live at https://devswag.io!
