### ISSUE TITLE
[Suggestion] Add code of conduct. 

### ISSUE THREAD

**Issue by kerrtrvs** [swapagarwal/swag-for-dev#30]
*No description provided.*

**Comment by rbstrachan** [comment]
**The Contributor Covenant Code of Conduct** is always a good idea for projects like these.
 Although the majority of the community that contributes to projects like cause no problems, the CCCoC assures people of minorities, like myself, that this project and the people behind it are here to contribute, not to hinder.
I completely agree - this should be implemented.

**Comment by Convery** [comment]
Please stop trying to poison every single project with your ideology.  It's code, or in this case a bunch of links, no one should need to read over a page of arbitrary rules to ensure that their contribution sits well with a small, but loud, group of people. If someone using an eggplant emoji in a commit message constitutes a hindrance for you, you may want to consider professional help. It's your problem, and you can't expect the world to accommodate your sensibilities.

**Comment by vikaspotluri123** [comment]
Hey @Convery, your comment suggests exactly why a code of conduct could be necessary. Instead of explaining why you don't think it's necessary to have a code of conduct, you impugned the character of both @ktrvs and @rbstrachan. All they suggested was the use of some kind of code of conduct (which could be a paragraph), with the suggestion of a well-established CoC, which although might be longer, is also more widely used, meaning people that use it don't have to read it since they already know it.

> Please stop trying to poison every single project with your ideology

- Who did this? I searched for issues created by both @rbstrachan and @ktrvs and I haven't seen anything suggesting they're serial CoC advocators
- [GitHub](https://github.com/swapagarwal/swag-for-dev/community) itself suggests a code of conduct, so this isn't really a super novel idea. If you have an issue with what GitHub does, feel free to take it up with them or leave the platform. Repositories like this are the definition of community-driven projects, and a well-structured community will ensure everything works better for everyone

**Comment by rbstrachan** [comment]
@convery You have misunderstood me. I have no problem with eggplant emoji's. I'm not asking for people to stop having funny conversations. I was referring to the people who deliberately post nonsense issues and PR's for the sake of it, which hinders the project instead of contributing helpfully. 🍆 :)

**Comment by Convery** [comment]
> GitHub itself suggests a code of conduct, so this isn't really a super novel idea. If you have an issue with what GitHub does, feel free to take it up with them or leave the platform.

So, you want a bunch of arbitrary rules for contributors added to a specific repository to ensure inclusiveness and that everyone feels welcome. Yet think that anyone that disagrees with adding them to the repository should just leave the entire platform. That sure does sound like someone arguing the merits of having the rules rather than simply pushing it for ideological reasons.

**Comment by vikaspotluri123** [comment]
I haven't stated my opinion relating to Codes of Conduct for this repository because frankly, I don't care either way. This issue relates specifically to a Code of Conduct, so I'm not going to go off topic by responding to meta discussions about subpar word choice. If you want to have that discussion, feel free to directly contact me

That being said, if you concrete points to why a CoC for this repo is good or bad, feel free to outline them

**Comment by Convery** [comment]
> I haven't stated my opinion relating to Codes of Conduct for this repository because frankly, I don't care either way.

Except that you think people commenting on applying a bunch of arbitrary rules on a large swath of people to appease a tiny minority that can't cope with eggplants is why it's necessary to have one.

**Comment by rbstrachan** [comment]
I believe you have served as a prime example of why a CoC is needed for this project. If you (@Convery) have a problem with the implementation of a CoC, say so in a meaningful way, instead of constantly arguing about points of view and eggplant emoji's (?). By not doing so, you are not contributing, but hindering.

To clarify, I believe you misunderstood my initial comment. I am not against people using emoji's of any sort, or having any kind of discussion. My point was that there exists a certain group of people who (deliberately or otherwise) hinder the progress and efficiency of the project by arbitrarily posting issues and PR's instead of meaningfully contributing to the project. A CoC would go a long way to helping those that would normally adversely affect the productivity of the project publish something that is genuinely helpful.

A CoC is not a set of strict rules that dictates what you can or cannot do, it is simply there to help people understand how the project expects people to conduct themselves. It does not say that you cannot use the eggplant emoji. It does not say that you cannot talk about certain topics. It merely prevents (to a degree) the amount of not-useful issues and pull requests submitted by directing peoples attention to documents like `readme.md`, `contributing.md` and `license.md`.

🍆

**Comment by kevin51jiang** [comment]
OK, let's settle down, shall we? Both sides have valid arguments of their own, but I think we should be able to have a compromise. CoC should be as follows:

***

# swag-for-dev Code of Conduct

## Section 1

In the interest of fostering an open and welcoming environment, we as a community have one simple rule.

Don't be a dick.

## Section 2

See section 1.
