### ISSUE TITLE
Run tests faster

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/swag-for-dev#385]
- [x] I've checked that this isn't a duplicate issue.

Right now, it takes around 2-3 minutes to run all the tests. Brainstorm on how can we achieve the same in seconds.

**Comment by maybebored** [comment]
I'm not sure what you mean by run all the tests. I saw one test file. Examining the code in `data.spec.js` it seems we are checking for a 200 response for:
1. reference url of swag event
2. image url of swag event

_Personally I think checking for the validity of the image url is redundant, we could always render something fallback if the image could not be loaded._ 

However to tackle the issue I propose the following:
Instead of a `forEach` loop that executes the test for each swag event synchronously, we should try to make it asynchronous and fail early, thereby at least stopping the test if even one URL cannot be reached.

I can implement something and raise a PR if you are happy with this idea.

On another note why do you 2-3 minutes is too long? If I understand your motive maybe we can approach this differently. (I learnt the hard way not everything is about code)

**Comment by vikaspotluri123** [comment]
What @swapagarwal means is these tests can be parallelized. For example, sites go down at times, so we have to wait 6.5s before the test fails. During those 6.5s, none of the other tests can run.

What we'd like to do is run multiple tests at once, e.g. test 3 opportunities at the same time. That way, if one of the links fails, we'll still have 2 runners pushing forward.

2-3 minutes is considered long because there aren't really that many tests

**Comment by driver-by** [comment]
Hey guys, I've tried to use mocha.parallel and it worked pretty good! I've just added a PR #415.
Let me know if it's ok.
