### ISSUE TITLE
Whats happening with the TravisCI

### ISSUE THREAD

**Issue by sampoder** [swapagarwal/swag-for-dev#511]
- [x] I've checked that this isn't a duplicate issue.

Seems to not be working on the commits even though it's building on Netlify.

**Comment by vikaspotluri123** [comment]
Hey @sampoder 👋 

CI checks every image and url ref to ensure they're still alive. Since the requests come from Travis, sometimes requests fail. We usually check the logs to make sure nothings gone awry before ignoring failing builds. Our switch to Github Actions (#365) will better show what the issue is

**Comment by sampoder** [comment]
Hmmmm ok... Thanks!

**Comment by aslafy-z** [comment]
Just applied a workaround with #25
